export const projects = [
  {
    //fundamentos
    name: "Mysterious Letter",
    category: "basis",
    describe: "Dado um valor digitado em um campo de texto, apresentar as palavras com uma aparência de uma carta onde cada palavra possui uma estilização própria, similar uma carta de recorte de revistas",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    banner: "/projectsimg/basis/mysterious-letter.png",
    instructions: "Para testar em sua máquina, clone o repositório e abra o html",
    repo: "https://github.com/JoseACSouza/mysterious-letter",
    demo: "",
    main: false,
  },
  {
    name: "Color Guess",
    category: "basis",
    describe: "- Nesta aplicação deverá ser possível jogar um jogo de adivinhação de cores onde: Dentro de uma possibilidade de cores o jogador deverá tentar adivinhar qual cor foi aleatoriamente selecionada como a cor certa; A paleta de cores deve ser apresentada por círculos coloridos; Deverá existir um botão para iniciar e reiniciar o jogo; Ao selecionar uma cor um texto deverá informar se você acertou ou não a cor correta.",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    banner: "/projectsimg/basis/color-guess.png",
    instructions: "Para testar em sua máquina, clone o repositório e abra o html",
    repo: "https://github.com/JoseACSouza/color-guess",
    demo: "",
    main: false,
  },
  {
    name: "To do List",
    category: "basis",
    describe: "Cria uma lista de tarefas simples e funcional",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    banner: "/projectsimg/basis/todo-list.png",
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e abra o html",
    repo: "https://github.com/JoseACSouza/todo-list",
    demo: "",
    main: false,
  },
  {
    name: "Meme Generator",
    category: "basis",
    describe: "Utiliza os elementos JS, HTML e CSS para criar uma fábrica de memes, com uma imagem e um texto",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    banner: "/projectsimg/basis/meme-generator.png",
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e abra o html",
    repo: "https://github.com/JoseACSouza/meme-generator",
    demo: "",
    main: false,
  },
  {
    name: "JS Unit Tests",
    category: "basis",
    describe: "Testes utilizando Jest para verificar a funcionalidade das funções",
    stacks: ["Jest", "NodeJS"],
    banner: "/projectsimg/basis/js-unit.png",
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e rode os tests unitários com npm run tests",
    repo: "https://github.com/JoseACSouza/js-unit-tests",
    demo: "",
    main: false,
  },
  {
    name: "Pixels Art",
    category: "basis",
    describe: "Um editor de arte com pixels em que a pessoa usuária poderá escolher uma cor em uma paleta de cores e poderá pintar o que quiser em um quadro branco 🎨 🧑‍🎨",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e abra o html",
    banner: "/projectsimg/basis/pixel-art.png",
    repo: "https://github.com/JoseACSouza/pixels-art",
    demo: "",
    main: false,
  },
  {
    name: "Playground Functions",
    category: "basis",
    describe: "Implementar o código de funções que resolvem problemas com respostas pré-determinadas. Utilizando a lógica de programação para ajudar na análise de cada problema e resposta esperada, facilitando a implementação do código de cada uma das funções.",
    stacks: ["JavaScript"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e utilize algum code runner para testar se os objetivos foram atingidos",
    banner: "/projectsimg/basis/zoo-playground-functions.png",
    repo: "https://github.com/JoseACSouza/playground-functions",
    demo: "",
    main: false,
  },
  {
    name: "Trybewarts",
    category: "basis",
    describe: "Uma página de formulário da Escola de Magia de Trybewarts, em que as pessoas estudantes poderão enviar seus feedbacks sobre ela. O tema desse projeto é baseado na obra 'Harry Potter', de J. K. Rowling, já que programar é o mais próximo que podemos chegar de algo verdadeiramente mágico! Mas não se preocupe se não tiver conhecimento sobre o universo da obra original, pois essa é uma versão própria da Escola de Bruxaria",
    stacks: ["JavaScript", "HTML5", "CSS3"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e abra o html",
    banner: "/projectsimg/basis/trybewarts.png",
    repo: "https://github.com/JoseACSouza/trybewarts",
    demo: "",
    main: false,
  },
  {
    name: "Zoo Functions",
    category: "basis",
    describe: "Funções que buscam informações sobre os animais do zoológico como: espécie e local de origem. Além disso, você também vai buscar dados sobre as pessoas que colaboram com a manutenção e cuidado do zoológico 🧑‍🌾, sempre testando as funções para manter sempre o código confiável e com boa performance.",
    stacks: ["JavaScript", "Jest", "NodeJS"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e utilize algum code runner para testar se os objetivos foram atingidos",
    banner: "/projectsimg/basis/zoo-playground-functions.png",
    repo: "https://github.com/JoseACSouza/zoo-functions",
    demo: "",
    main: false,
  },
  //front-end
  {
    name: "Solar System",
    category: "Front-End",
    describe: "Neste projeto você desenvolverá um modelo do sistema solar! Ao utilizar essa aplicação, uma pessoa usuária deverá ser capaz de: Visualizar todos os planetas do sistema solar renderizados na tela; Visualizar todas as cartas com informações sobre missões espaciais;",
    stacks: ["JavaScript", "ReactJS"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/solar-system.png",
    repo: "https://github.com/JoseACSouza/solar-system",
    demo: "",
    main: false,
  },
  {
    name: "Super Trunfo Medieval",
    category: "Front-End",
    describe: "Neste projeto desenvolvo um deck-builder de um jogo de super trunfo",
    stacks: ["JavaScript", "ReactJS", "CSS3"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/tryunfo.png",
    repo: "https://github.com/JoseACSouza/project_tryunfo",
    demo: "",
    main: false,
  },
  {
    name: "Shopping Cart",
    category: "Front-End",
    describe: "Carrinho de compras com aquisição dos produtos do mercado livre",
    stacks: ["JavaScript", "ReactJS", "CSS3"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/shopping-cart.png",
    repo: "https://github.com/JoseACSouza/shopping_cart",
    demo: "",
    main: false,
  },
  {
    name: "React Testing Library",
    category: "Front-End",
    describe: "Neste projeto eu desenvolvo os testes para a aplicação de pokedéx feita com react",
    stacks: ["JavaScript", "Jest", "ReactJS", "React Testing Library"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e rode os tests unitários com npm run tests",
    banner: "/projectsimg/frontend/rtl.png",
    repo: "https://github.com/JoseACSouza/rtl_tests",
    demo: "",
    main: false,
  },
  {
    name: "TrybeTunes",
    category: "Front-End",
    describe: "Uma aplicação capaz de reproduzir músicas das mais variadas bandas e artistas, criar uma lista de músicas favoritas e editar o perfil da pessoa usuária logada. Essa aplicação será capaz de: - Fazer login; - Pesquisar por uma banda ou artista;  - Listar os álbuns disponíveis dessa banda ou artista; - Visualizar as músicas de um álbum selecionado; - Reproduzir uma prévia das músicas deste álbum; - Favoritar e desfavoritar músicas; - Ver a lista de músicas favoritas; - Ver o perfil da pessoa logada; - Editar o perfil da pessoa logada;",
    stacks: ["JavaScript", "ReactJS", "TailwindCSS"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/trybe-tunes.png",
    repo: "https://github.com/JoseACSouza/trybetunes",
    demo: "",
    main: true,
  },
  {
    name: "Trybewallet",
    category: "Front-End",
    describe: "Uma carteira de controle de gastos com conversor de moedas, ao utilizar essa aplicação um usuário deverá ser capaz de: - Adicionar, remover e editar um gasto; - Visualizar uma tabelas com seus gastos; - Visualizar o total de gastos convertidos para uma moeda de escolha;",
    stacks: ["JavaScript", "Jest", "ReactJS", "TailwindCSS"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/trybe-wallet.png",
    repo: "https://github.com/JoseACSouza/trybewallet",
    demo: "",
    main: false,
  },
  {
    name: "StarWars Planet Search",
    category: "Front-End",
    describe: "Uma página dos principais planetas da saga de StarWars e suas respectivas informações",
    stacks: ["JavaScript", "Jest", "ReactJS", "TailwindCSS"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'npm install' e então inicie o app web com 'npm start'",
    banner: "/projectsimg/frontend/star-wars.png",
    repo: "https://github.com/JoseACSouza/starwars-planets-search",
    demo: "",
    main: false,
  },
  //data-science
  {
    name: "Algorithms",
    category: "Data-Science",
    describe: "Projeto que resolvi problemas e otimizei algoritmos desenvolvendo a capacidade de implementar soluções para os mais diversos problemas do dia a dia!",
    stacks: ["Python"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'pip install'",
    banner: "/projectsimg/data-science/python.jpg",
    repo: "https://github.com/JoseACSouza/project-algorithms",
    demo: "",
    main: false,
  },
  {
    name: "Job Insights",
    category: "Data-Science",
    describe: "Neste projeto implementei análises a partir de um conjunto de dados sobre empregos.",
    stacks: ["Python"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'pip install'",
    banner: "/projectsimg/data-science/python.jpg",
    repo: "https://github.com/JoseACSouza/job-insights",
    demo: "",
    main: false,
  },
  {
    name: "TING (Trybe is not Google)",
    category: "Data-Science",
    describe: "Neste projeto implementei um programa que simule um algoritmo de indexação de documentos similar ao do Google. Seu programa deverá ser capaz de identificar ocorrências de termos em arquivos _TXT_. Para isso, o programa desenvolvido por você deverá ter dois módulos: - **Módulo de gerenciamento de arquivos** que permite anexar arquivos de texto (formato _TXT_) e;- **Módulo de buscas** que permite operar funções de busca sobre os arquivos anexados.",
    stacks: ["Python"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'pip install'",
    banner: "/projectsimg/data-science/python.jpg",
    repo: "https://github.com/JoseACSouza/ting",
    demo: "",
    main: false,
  },
  {
    name: "Restaurant Orders",
    category: "Data-Science",
    describe: "Projeto que resolve a seguinte situação problema: O Restaurante  🍝 🦐 Chapa Quente 🍛 🥘 precisa de você para finalizar sua ferramenta de construção de cardápios. O restaurante necessita desta ferramenta para que possa, de maneira simples, gerar seus cardápios considerando possíveis restrições alimentares e também a disponibilidade dos ingredientes em estoque. Hoje, a gestão das receitas e de estoque do restaurante acontece de forma muito ineficiente através de arquivos csv e, por essa razão, as pessoas fundadoras do estabelecimento desejam melhorar esta gestão; -Um primeiro time iniciou o desenvolvimento deste projeto e já preparou uma estrutura inicial para que você possa finalizar essa construção. Assim, ao longo deste projeto você será responsável por construir testes para classes já implementadas, implementará uma nova classe para mapear os pratos e suas respectivas receitas (ingredientes e quantidades), também implementará uma classe que gerará os cardápios que devem ser mostrados para as pessoas que frequentam o estabelecimento e outra que fará a gestão de estoque dos ingredientes.",
    stacks: ["Python", "Testes Python"],
    instructions: "Para testar em sua máquina, clone o repositório, instale as dependencias com 'pip install'",
    banner: "/projectsimg/data-science/python.jpg",
    repo: "https://github.com/JoseACSouza/restaurant-orders",
    demo: "",
    main: false,
  },

  //mobile
  {
    name: "Android Exchange",
    category: "Mobile",
    describe: "Uma aplicação Android de conversão de moedas que utiliza os dados da API [exchangerate.host](https://exchangerate.host). Esse aplicativo contêm o layout, a validação de estado dos compoentes e código de consumo de uma API Rest com Retrofit.",
    stacks: ["Kotlin"],
    instructions: "Abra o projeto no Android studio e rode em uma API 29",
    banner: "/projectsimg/mobile/android.svg",
    repo: "https://github.com/JoseACSouza/android-cambio",
    demo: "",
    main: false,
  },
  {
    name: "Login Rede Social",
    category: "Mobile",
    describe: "Tela de login de uma rede social. Essa tela de login contém apenas o layout e as validações de interface, não se conectando nesse momento com nenhuma API.",
    stacks: ["Kotlin"],
    instructions: "Abra o projeto no Android studio e rode em uma API 29",
    banner: "/projectsimg/mobile/android.svg",
    repo: "https://github.com/JoseACSouza/login-social",
    demo: "",
    main: false,
  },
  {
    name: "Trybe Virtual Menu",
    category: "Mobile",
    describe: "Um aplicativo de um cardápio virtual, consistindo em duas telas: a primeira exibindo uma lista de itens e a segunda fornecendo detalhes do item selecionado.",
    stacks: ["Kotlin"],
    instructions: "Abra o projeto no Android studio e rode em uma API 29",
    banner: "/projectsimg/mobile/android.svg",
    repo: "https://github.com/JoseACSouza/trybe-virtual-menu",
    demo: "",
    main: false,
  },
  {
    name: "TRYBNB",
    category: "Mobile",
    describe: "Um aplicativo Android para criar e exibir as reservas feitas pelos hóspedes, utilizando os dados da API [restful-booker](https://restful-booker.herokuapp.com/apidoc/index.html). Este aplicativo inclui o layout, a validação de estados dos componentes e o código de consumo de uma API Rest com Retrofit, seguindo a arquitetura MVVM.",
    stacks: ["Kotlin"],
    instructions: "Abra o projeto no Android studio e rode em uma API 29",
    banner: "/projectsimg/mobile/trybnb.png",
    repo: "https://github.com/JoseACSouza/trybnb",
    demo: "",
    main: true,
  },

  //back-end
  {
    name: "All For One",
    category: "Back-End",
    describe: "Temos, nesse projeto, uma série de desafios com diferentes níveis de complexidade que devem ser resolvidos cada um em seu arquivo próprio.",
    stacks: ["MySQL", "Docker"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/all-for-one",
    demo: "", 
    main: false,
  },
  {
    name: "One For All",
    category: "Back-End",
    describe: "No projeto ***One For All***, usarei **algumas** tabelas para revisar e consolidar **todos** os principais conceitos vistos até o momento. Onde planilhas não normalizadas foram normalizadas e populadas em um banco de dados para executar queries com o intuito de encontrar as informações solicitadas.",
    stacks: ["MySQL", "Docker"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/one-for-all",
    demo: "",
    main: false,
  },
  {
    name: "Blogs Api",
    category: "Back-End",
    describe: "Neste projeto desenvolvi uma API e um banco de dados para a produção de conteúdo para um blog! Desenvolvi esta aplicação em `Node.js` usando o pacote `sequelize` para fazer um `CRUD` de posts.1. Desenvolvi endpoints que estarão conectados ao seu banco de dados seguindo os princípios do REST; 2. Para fazer um post é necessário usuário e login, portanto será trabalhada a **relação entre** `user` e `post`; 3. Será necessária a utilização de categorias para os posts, trabalhando, assim, a **relação de** `posts` para `categories` e de `categories` para `posts`.",
    stacks: ["MySQL", "Docker", "NodeJS", "Sequelize"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/blogs-api",
    demo: "",
    main: false,
  },
  {
    name: "Docker To Do List",
    category: "Back-End",
    describe: "Neste projeto irei: 1. **_Conteinerizar_** aplicações; 2. Criar uma conexão entre elas; 3. Orquestrar seu funcionamento. Temos [uma aplicação full-stack](docker/todo-app) neste repositório: um **aplicativo de tarefas**! Esta aplicação precisa ser conteinerizada para funcionar. Para isso desenvolverei os arquivos de configuração para cada frente específica: `Front-end`, `Back-end` e, no nosso caso, para um aplicativo de `teste` que valida se as aplicações estão se comunicando. Assim eu tive de criar as imagens para as aplicações e configurar essas imagens com o `docker-compose`. Para isto, você irá utilizar uma série de comandos do `docker` com diferentes níveis de complexidade.Cada comando deverá ser escrito em seu próprio arquivo.",
    stacks: ["Docker"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/docker-todo-list",
    demo: "",
    main: false,
  },
  {
    name: "Talker Manager",
    category: "Back-End",
    describe: "Irei construir uma aplicação de cadastro de talkers (palestrantes) em que será possível cadastrar, visualizar, pesquisar, editar e excluir informações. Para isso você deverá: 1. Desenvolver uma API de um `CRUD` (**C**reate, **R**ead, **U**pdate e **D**elete) de palestrantes (talkers) e; 2. Desenvolver alguns endpoints que irão ler e escrever em um arquivo utilizando o módulo `fs`.",
    stacks: ["MySQL", "Docker", "NodeJS", "Sequelize"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/talker-manager",
    demo: "",
    main: false,
  },
  {
    name: "Trybers and Dragons",
    category: "Back-End",
    describe: "Este projeto é um treinamento para POO. No universo de Trybers and Dragons - T&D, quase todos os seres que andam por essas terras pertencem a uma **raça** definida. As diversas raças (como, por exemplo, Élfica, Orc ou Anã) definem as características das personagens dentro do jogo desde a sua criação, como os seus pontos de vida e a sua destreza. No entanto, existem seres bestiais denominados **monstros** que não possuem uma raça específica, mas podem lutar. Alguns seres também possuem uma **energia** e, ao treinarem o uso da energia, passam a possuir um **arquétipo**. De modo geral, os arquétipos definem a vocação de uma personagem, suas habilidades e visão de mundo: como encaram as situações, exploram masmorras ou enfrentam monstros. Como exemplos de arquétipos presentes em T&D, podemos citar guerreiro, mago e necromante. Boa parte dos seres podem ser considerados lutadores, bastando para isso possuir alguns atributos específicos. Em muitas ocasiões podem acontecer lutas entre personagens diversas, bem como entre personagens e monstros. Agora, cabe a você, nobre ~~dev~~, explorar essas terras e cumprir as quests que surgirão ao longo da sua incrível ~~jornada~~ leitura do README. **_Now, follow ~~the blind~~ the dungeon master!_**",
    stacks: ["POO", "Typescript"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/trybers-and-dragons",
    demo: "",
    main: false,
  },
  {
    name: "Trybesmith",
    category: "Back-End",
    describe: "Para este projeto, irei criar uma loja de itens medievais, como aquelas espadas feitas sob encomenda para uma pessoa específica, no formato de uma _API_, utilizando _Typescript_ e _Sequelize_.Irei desenvolver as camadas de _Service_ e _Controllers_ da aplicação em meu código, utilizando _JWT_ para autenticar algumas rotas, além de testes para garantir o correto funcionamento delas. A aplicação terá _endpoints_ que darão suporte a operações de criação, leitura e atualização de informações. ~Aplicação sem Front-End~",
    stacks: ["MySQL", "Docker", "NodeJS", "Sequelize", "Typescript", "Tests"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/trybesmith",
    demo: "",
    main: false,
  },
  {
    name: "Trybe Futebol Clube - TFC",
    category: "Back-End",
    describe: "O `TFC` é um site informativo sobre partidas e classificações de futebol! ⚽️ No time de desenvolvimento do `TFC`, meu *squad* ficou responsável por desenvolver uma API (utilizando o método `TDD`) e também integrar *- através do docker-compose -* as aplicações para que elas funcionem consumindo um banco de dados. Nesse projeto, irei construir **um back-end dockerizado utilizando modelagem de dados através do Sequelize**. Seu desenvolvimento deve **respeitar regras de negócio** providas no projeto e **sua API deve ser capaz de ser consumida por um front-end já provido nesse projeto**.",
    stacks: ["MySQL", "Docker", "NodeJS", "Sequelize", "Typescript", "Tests"],
    instructions: "Para testar em sua máquina, clone o repositório e use os comandos npm install, docker-compose up",
    banner: "/projectsimg/back-end/back-end.png",
    repo: "https://github.com/JoseACSouza/trybe-futebol-clube",
    demo: "",
    main: false,
  },

  //personal projects
  {
    name: "Meu primeiro app Laravel",
    category: "Back-End",
    describe: "Este projeto é um app simples com o intuito de aprender a utlizar o ecossistema Laravel.",
    stacks: ["MySQL", "Docker", "PHP", "Laravel", "ReactJS", "TailwindCSS"],
    instructions: "Esse projeto foi meu primeiro app em laravel e meu primeiro contato com php",
    banner: "/projectsimg/personal-projects/laravel.webp",
    repo: "https://github.com/JoseACSouza/curso-laravel-10",
    demo: "",
    main: false
  },
  {
    name: "Treinamento - COM3",
    category: "Back-End",
    describe: "Este projeto consiste em criar uma aplicação e seu banco de dados que funcione como uma 'rede social' de uma empresa. Funcionará com posts e suas categorias, além de filtros por categorias e um sistema de 'níveis de acesso', onde apenas a staff da empresa consiga editar e apagar qualquer post além de adicionar ou remover categorias.",
    stacks: ["MySQL", "Docker", "PHP", "Laravel", "ReactJS", "TailwindCSS"],
    instructions: "Para testar esse aplicativo fullstack, é necessário primeiramente instalar as dependencias com npm install, depois iniciar o banco de dados com o sail utilizando o comando ./vendor/bin/sail up e por fim rodá-lo com npm run dev",
    banner: "/projectsimg/personal-projects/com3.png",
    repo: "https://github.com/JoseACSouza/Treinamento-COM3", 
    demo: "",
    main: true,
  },
  {
    name: "Mobile COM3",
    category: "Mobile",
    describe: "Este projeto consiste em criar uma aplicação mobile do aplicativo web, cuja função seja simplificada, (sem a versão da staff). Esse aplicativo tem um destaque de funcionar sem internet, sincronizando o banco de dados quando for reestabelecidada conexão. PS: Essa aplicação utiliza o banco de dados da aplicação Treinamento COM3, sendo necessário baixá-la e deixar o banco de dados up para funcionar esta.",
    stacks: ["React Native", "TailwindCSS", "WatermelonDB"],
    instructions: "Para a visualização deste app é necessário a instalação do expo e do android studio com um API 34, após isso, deve-se utilizar o comando npm install e então iniciar o emulador de celular criado então usar o comando npx expo start. AVISO IMPORTANTE: O banco de dados desse app mobile está na aplicação [Treinamento - COM3](https://github.com/JoseACSouza/Treinamento-COM3) ou seja, depende da mesma estar com os containers up para funcionar corretamente",
    banner: "/projectsimg/mobile/com3.png",
    repo: "https://github.com/JoseACSouza/Mobile-TreinamentoCOM3", 
    demo: "",
    main: false,
  },
]
